// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyPlanner.Infrastructure.Data;

#nullable disable

namespace WeeklyPlanner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WeeklyPlanner.Core.Models.BacklogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacklogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            Description = "Client reported login issue",
                            IsActive = true,
                            Title = "Fix login bug"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Description = "New client feature",
                            IsActive = true,
                            Title = "Customer dashboard"
                        },
                        new
                        {
                            Id = 3,
                            Category = 2,
                            Description = "Tech debt cleanup",
                            IsActive = true,
                            Title = "Refactor auth module"
                        },
                        new
                        {
                            Id = 4,
                            Category = 2,
                            Description = "Performance improvement",
                            IsActive = true,
                            Title = "Database indexing"
                        },
                        new
                        {
                            Id = 5,
                            Category = 3,
                            Description = "Research ML options",
                            IsActive = true,
                            Title = "AI recommendation spike"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            Description = "R&D for cost reduction",
                            IsActive = true,
                            Title = "Cloud cost analysis"
                        });
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLead = true,
                            Name = "Team Lead"
                        },
                        new
                        {
                            Id = 2,
                            IsLead = false,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 3,
                            IsLead = false,
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.PlanEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("BacklogItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlannedHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyPlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacklogItemId");

                    b.HasIndex("WeeklyPlanId");

                    b.ToTable("PlanEntries");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.WeekCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Category1Percent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Category2Percent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Category3Percent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlanningDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeekCycles");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.WeeklyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FrozenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekCycleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("WeekCycleId");

                    b.ToTable("WeeklyPlans");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.PlanEntry", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Models.BacklogItem", "BacklogItem")
                        .WithMany("PlanEntries")
                        .HasForeignKey("BacklogItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Models.WeeklyPlan", "WeeklyPlan")
                        .WithMany("PlanEntries")
                        .HasForeignKey("WeeklyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacklogItem");

                    b.Navigation("WeeklyPlan");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.WeeklyPlan", b =>
                {
                    b.HasOne("WeeklyPlanner.Core.Models.Member", "Member")
                        .WithMany("WeeklyPlans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyPlanner.Core.Models.WeekCycle", "WeekCycle")
                        .WithMany("WeeklyPlans")
                        .HasForeignKey("WeekCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WeekCycle");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.BacklogItem", b =>
                {
                    b.Navigation("PlanEntries");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.Member", b =>
                {
                    b.Navigation("WeeklyPlans");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.WeekCycle", b =>
                {
                    b.Navigation("WeeklyPlans");
                });

            modelBuilder.Entity("WeeklyPlanner.Core.Models.WeeklyPlan", b =>
                {
                    b.Navigation("PlanEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
