name: CD — Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    name: Deploy Angular → Azure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: weekly-planner-ui/package-lock.json

      - name: Install dependencies
        working-directory: weekly-planner-ui
        run: npm ci --legacy-peer-deps

      - name: Build Angular app
        working-directory: weekly-planner-ui
        run: npm run build -- --configuration production

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B4DDFA5DC2747A5948EC915AC78F0E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1B10DEA64B84CFA8956B01676266D02 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69955EE110324AB3AC3FB638A8315876 }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: weekly-planner-ui-akshay
          package: weekly-planner-ui/dist/weekly-planner-ui/browser